name = "meu-portfolio"
compatibility_date = "2024-04-27"

[build]
  command = "next build"
  output_dir = ".vercel/output/static"

[build.upload]
  format = "service-worker"  # Isso é necessário para funcionar no Cloudflare Pages

[env.production]
  nodejs_compatibility = true  # Certifique-se de ativar essa compatibilidade